# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1118bc3669881b638fb966e30e7f16a438d1906f1fb36c11aeccd27ce2059a71ae25dd1c443bad301046693ac636fe4039249f1a6641d16755eee197e9c052d3

test:
  secret_key_base: 43cc072c75a04b6bab0a6e88edde0e9cb1ea7eb5ec05e60d60359a9a5e099f11a840756af9563e9316967e61f75ecc62d56ca53fe13305d2600ff6655cf0e2bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
